# Generated by Django 5.0.4 on 2024-05-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assistants',
            new_name='Assistant',
        ),
    ]
